# TheSportsDB league IDs for all 54 UEFA first-tier leagues.
# (Liechtenstein excluded — no domestic league; clubs play in Swiss system)
#
# season_type:
#   "winter" – season spans two calendar years (Aug–May), e.g. "2025-2026"
#   "summer" – season runs within one calendar year (Apr–Nov), e.g. "2025"

LEAGUES = {
    # ── Top 5 (pinned) ───────────────────────────────────────────────────────
    "English Premier League":       {"id": 4328, "country": "England",     "flag": "🏴󠁧󠁢󠁥󠁮󠁧󠁿", "season_type": "winter",
                                     "season_end": "24 May 2026",
                                     "tiebreakers": ["gd", "gf", "h2h_pts", "h2h_away_gf", "playoffs"],
                                     "european_spots": {1: "UCL - LS", 2: "UCL - LS", 3: "UCL - LS", 4: "UCL - LS", 5: "UEL - LS", 6: "UECL - PO"}},
    "Italian Serie A":              {"id": 4332, "country": "Italy",       "flag": "🇮🇹", "season_type": "winter",
                                     "season_end": "24 May 2026",
                                     "tiebreakers": ["h2h_pts", "h2h_gd", "gd", "gf", "playoffs_title_or_rel3"],
                                     "european_spots": {1: "UCL - LS", 2: "UCL - LS", 3: "UCL - LS", 4: "UCL - LS", 5: "UEL - LS", 6: "UECL - PO"}},
    "Spanish La Liga":              {"id": 4335, "country": "Spain",       "flag": "🇪🇸", "season_type": "winter",
                                     "season_end": "24 May 2026",
                                     "tiebreakers": ["h2h_pts", "h2h_gd", "gd", "gf", "fair_play"],
                                     "european_spots": {1: "UCL - LS", 2: "UCL - LS", 3: "UCL - LS", 4: "UCL - LS", 5: "UEL - LS", 6: "UECL - PO"}},
    "German Bundesliga":            {"id": 4331, "country": "Germany",     "flag": "🇩🇪", "season_type": "winter",
                                     "season_end": "16 May 2026",
                                     "tiebreakers": ["gd", "gf", "h2h_pts", "h2h_away_gf", "away_gf", "playoffs"],
                                     "european_spots": {1: "UCL - LS", 2: "UCL - LS", 3: "UCL - LS", 4: "UCL - LS", 5: "UEL - LS", 6: "UECL - PO"},
                                     "zone_notes": {"relegation playoff": "16th plays two-legged play-off against 3rd-placed team from 2. Bundesliga. Higher-ranked team plays second leg at home."}},
    "French Ligue 1":               {"id": 4334, "country": "France",      "flag": "🇫🇷", "season_type": "winter",
                                     "season_end": "16 May 2026",
                                     "tiebreakers": ["gd", "h2h_pts", "h2h_gd", "h2h_gf", "h2h_away_gf", "gf", "away_gf", "fair_play"],
                                     "european_spots": {1: "UCL - LS", 2: "UCL - LS", 3: "UCL - LS", 4: "UEL - PO", 5: "UEL - QR3", 6: "UECL - PO"},
                                     "zone_notes": {"relegation playoff": "16th plays two-legged play-off against 3rd-placed team from Ligue 2. Away goals do not apply; extra time and penalties if level after two legs."}},
    # ── Rest (alphabetical) ──────────────────────────────────────────────────
    "Albanian Superliga":           {"id": 4617, "country": "Albania",     "flag": "🇦🇱", "season_type": "winter",
                                     "season_end": "24 May 2026",
                                     "tiebreakers": ["h2h_pts", "h2h_gd", "h2h_gf", "gd", "gf", "draw"],
                                     "european_spots": {1: "UCL - QR1", 2: "UECL - QR2", 3: "UECL - QR2"},
                                     "final_four": True,
                                     "zones": {
                                         "Final Four": [1, 2, 3, 4],
                                         "Relegation Play-off": [8],
                                         "Relegation": [9, 10],
                                     },
                                     "zone_notes": {
                                         "final four": "Top 4 teams play a knock-out Final Four to determine the champion. Draw is conducted with two seeded teams (1st, 2nd) and two unseeded (3rd, 4th). Seeded teams cannot meet in the semi-finals. If level after 90 minutes in a semi-final, the higher-ranked team advances. The final is decided by extra time and penalties if necessary.",
                                         "relegation play-off": "The 8th ranked team qualifies to the play-off round, which they play against the Kategoria e Parë play-off winner.",
                                     }},
    "Andorran Primera Divisió":     {"id": 4618, "country": "Andorra",     "flag": "🇦🇩", "season_type": "winter",
                                     "season_end": "17 May 2026",
                                     "tiebreakers": ["h2h_pts", "h2h_gd", "h2h_gf", "gd", "gf"],
                                     "european_spots": {1: "UCL - QR1", 2: "UECL - QR2"}},
    "Armenian Premier League":      {"id": 4619, "country": "Armenia",     "flag": "🇦🇲", "season_type": "winter",
                                     "tiebreakers": ["h2h_pts", "h2h_gd", "h2h_gf", "wins", "gd", "less_red_cards", "less_yellow_cards", "fair_play", "draw"],
                                     "european_spots": {1: "UCL - QR1", 2: "UECL - QR2", 3: "UECL - QR2"}},
    "Austrian Bundesliga":          {"id": 4621, "country": "Austria",     "flag": "🇦🇹", "season_type": "winter",
                                     "season_end": "24 May 2026",
                                     "tiebreakers": ["h2h_pts", "h2h_gd", "h2h_gf", "gd", "gf"],
                                     "european_spots": {1: "UCL - PO", 2: "UEL - PO", 3: "UECL - QR3", 4: "UECL - QR3"},
                                     "split_round": 22, "n_champ": 5, "pts_factor": 0.5,
                                     "zone_notes": {"relegation": "Last-placed team in the Relegation Round plays a two-legged play-off against 2nd-placed team from 2. Liga. Home team in first leg is the lower-ranked club."}},
    "Azerbaijani Premier League":   {"id": 4693, "country": "Azerbaijan",  "flag": "🇦🇿", "season_type": "winter",
                                     "tiebreakers": ["wins", "gd", "gf", "h2h_pts", "h2h_gd", "disciplinary", "draw"],
                                     "european_spots": {1: "UCL - QR2", 2: "UECL - PO", 3: "UECL - QR3"}},
    "Belarus Vyscha Liga":          {"id": 4622, "country": "Belarus",     "flag": "🇧🇾", "season_type": "summer",
                                     "tiebreakers": ["h2h_pts", "h2h_gd", "h2h_gf", "gd", "wins", "gf"],
                                     "european_spots": {1: "UCL - QR1", 2: "UECL - QR2"}},
    "Belgian Pro League":           {"id": 4338, "country": "Belgium",     "flag": "🇧🇪", "season_type": "winter",
                                     "season_end": "17 May 2026",
                                     "tiebreakers": ["gd", "gf", "away_gf"],
                                     "european_spots": {1: "UCL - LS", 2: "UCL - PO (LP)", 3: "UEL - QR3", 4: "UECL - QR3"},
                                     "split_round": 30, "n_champ": 6, "pts_factor": 0.5,
                                     "zone_notes": {"europa": "Play-Off II: 7th–12th split into two groups of 3 (7th/9th/11th vs 8th/10th/12th). Each group plays a round-robin. Group winners meet in a single-leg final for one Conference League spot.", "relegation": "Bottom 4 play a round-robin (carrying full points). Last place is relegated; 15th plays two-legged play-off vs 2nd of Challenger Pro League."}},
    "Bosnian Premier Liga":         {"id": 4624, "country": "Bosnia",      "flag": "🇧🇦", "season_type": "winter",
                                     "season_end": "31 May 2026",
                                     "tiebreakers": ["gd", "gf", "h2h_pts", "h2h_gd", "h2h_away_gf", "h2h_gf", "playoffs"],
                                     "european_spots": {1: "UCL - QR1", 2: "UECL - QR2", 3: "UECL - QR2"}},
    "Bulgarian First League":       {"id": 4626, "country": "Bulgaria",    "flag": "🇧🇬", "season_type": "winter",
                                     "season_end": "29 May 2026",
                                     "tiebreakers": ["h2h_pts", "h2h_gd", "h2h_gf", "h2h_away_gf", "gd", "gf", "fair_play", "draw"],
                                     "european_spots": {1: "UCL - QR2", 2: "UECL - PO", 3: "UECL - PO"},
                                     "split_round": 26, "n_champ": 4, "n_mid": 4, "pts_factor": 1.0},
    "Croatian First League":        {"id": 4629, "country": "Croatia",     "flag": "🇭🇷", "season_type": "winter",
                                     "season_end": "23 May 2026",
                                     "tiebreakers": ["h2h_pts", "h2h_gd", "h2h_gf", "gd", "gf", "playoffs"],
                                     "european_spots": {1: "UCL - QR3", 2: "UECL - PO", 3: "UECL - PO"}},
    "Czech First League":           {"id": 4631, "country": "Czech Rep.",  "flag": "🇨🇿", "season_type": "winter",
                                     "season_end": "31 May 2026",
                                     "tiebreakers": ["h2h_pts", "h2h_gd", "h2h_gf", "gd", "gf", "fair_play", "draw"],
                                     "european_spots": {1: "UCL - LS", 2: "UCL - PO (LP)", 3: "UEL - QR3", 4: "UECL - QR3"},
                                     "split_round": 30, "n_champ": 10, "n_mid": 3, "pts_factor": 1.0},
    "Cypriot First Division":       {"id": 4630, "country": "Cyprus",      "flag": "🇨🇾", "season_type": "winter",
                                     "tiebreakers": ["h2h_pts", "h2h_gd", "h2h_gf", "h2h_away_gf", "gd", "gf", "playoffs"],
                                     "european_spots": {1: "UCL - QR3", 2: "UECL - PO", 3: "UECL - PO"},
                                     "split_round": 26, "n_champ": 6, "pts_factor": 1.0},
    "Danish Superliga":             {"id": 4340, "country": "Denmark",     "flag": "🇩🇰", "season_type": "winter",
                                     "season_end": "26 May 2026",
                                     "tiebreakers": ["gd", "gf", "away_gf", "playoffs", "draw"],
                                     "european_spots": {1: "UCL - QR3", 2: "UECL - PO", 3: "UECL - PO"},
                                     "split_round": 22, "n_champ": 6, "pts_factor": 1.0,
                                     "zone_notes": {"relegation": "11th is directly relegated. 12th plays two-legged play-off against 2nd of the 1st Division. Higher-ranked club plays second leg at home."}},
    "Dutch Eredivisie":             {"id": 4337, "country": "Netherlands", "flag": "🇳🇱", "season_type": "winter",
                                     "season_end": "24 May 2026",
                                     "tiebreakers": ["less_losses", "gd", "gf", "h2h_pts", "h2h_gd", "h2h_away_gf", "playoffs"],
                                     "european_spots": {1: "UCL - LS", 2: "UCL - LS", 3: "UEL - PO", 4: "UEL - QR3", 5: "UECL - LS"},
                                     "zone_notes": {"play off": "5th vs 8th and 6th vs 7th in single-leg semi-finals at the higher-ranked club's ground. Single-leg final also at higher-ranked club's ground. Winner qualifies for Conference League."}},
    "Estonian Meistriliiga":        {"id": 4634, "country": "Estonia",     "flag": "🇪🇪", "season_type": "summer",
                                     "season_end": "8 November 2025",
                                     "tiebreakers": ["h2h_pts", "h2h_gd", "wins", "gd", "gf", "away_gf", "fair_play", "draw"],
                                     "european_spots": {1: "UCL - QR1", 2: "UECL - QR2", 3: "UECL - QR2"}},
    "Faroe Islands Premier League": {"id": 4635, "country": "Faroe Isl.",  "flag": "🇫🇴", "season_type": "summer",
                                     "season_end": "25 October 2025",
                                     "tiebreakers": ["gd", "gf"],
                                     "european_spots": {1: "UCL - QR1", 2: "UECL - QR2", 3: "UECL - QR2"}},
    "Finnish Veikkausliiga":        {"id": 4636, "country": "Finland",     "flag": "🇫🇮", "season_type": "summer",
                                     "season_end": "26 October 2025",
                                     "tiebreakers": ["h2h_pts", "h2h_gd", "h2h_gf", "h2h_away_gf", "gd", "gf", "fair_play", "draw"],
                                     "european_spots": {1: "UCL - QR1", 2: "UECL - QR2", 3: "UECL - QR2"},
                                     "split_round": 22, "n_champ": 6, "pts_factor": 1.0,
                                     "zone_notes": {"relegation": "11th is directly relegated. 12th plays two-legged play-off against a Ykkönen team. Higher-ranked club plays second leg at home."}},
    "Georgian Erovnuli Liga":       {"id": 4638, "country": "Georgia",     "flag": "🇬🇪", "season_type": "summer",
                                     "tiebreakers": ["h2h_pts", "h2h_gd", "h2h_gf", "h2h_away_gf", "gd", "gf"],
                                     "european_spots": {1: "UCL - QR1", 2: "UECL - QR2", 3: "UECL - QR2"}},
    "Gibraltar National League":    {"id": 4964, "country": "Gibraltar",   "flag": "🇬🇮", "season_type": "winter",
                                     "season_end": "26 April 2026",
                                     "tiebreakers": ["h2h_pts", "h2h_gd", "h2h_gf", "h2h_away_gf", "gd", "gf", "fair_play", "draw"],
                                     "european_spots": {1: "UCL - QR1", 2: "UECL - QR2"},
                                     "split_round": 22, "n_champ": 6, "pts_factor": 1.0},
    "Greek Super League":           {"id": 4336, "country": "Greece",      "flag": "🇬🇷", "season_type": "winter",
                                     "season_end": "21 May 2026",
                                     "tiebreakers": ["h2h_pts", "h2h_gd", "gd", "gf", "playoffs"],
                                     "european_spots": {1: "UCL - PO", 2: "UEL - PO", 3: "UEL - QR3", 4: "UECL - QR3"},
                                     "split_round": 26, "n_champ": 4, "n_mid": 4, "pts_factor": 0.5,
                                     "zone_notes": {"europa": "5th–8th play a Conference League play-off round-robin (points halved). Winner qualifies for Conference League.", "relegation": "Bottom two are directly relegated. 12th–13th play two-legged play-offs against Super League 2 teams."}},
    "Hungarian NB I":               {"id": 4690, "country": "Hungary",     "flag": "🇭🇺", "season_type": "winter",
                                     "season_end": "17 May 2026",
                                     "tiebreakers": ["wins", "gd", "gf", "h2h_pts", "h2h_gd", "fair_play", "draw"],
                                     "european_spots": {1: "UCL - QR2", 2: "UECL - PO", 3: "UECL - PO"}},
    "Icelandic Úrvalsdeild":        {"id": 4642, "country": "Iceland",     "flag": "🇮🇸", "season_type": "summer",
                                     "tiebreakers": ["gd", "gf", "h2h_pts", "h2h_gd", "h2h_gf", "h2h_away_gf"],
                                     "european_spots": {1: "UCL - QR2", 2: "UECL - PO", 3: "UECL - QR3"}},
    "Irish Premier Division":       {"id": 4643, "country": "Ireland",     "flag": "🇮🇪", "season_type": "summer",
                                     "season_end": "1 November 2025",
                                     "tiebreakers": ["gd", "gf"],
                                     "european_spots": {1: "UCL - QR2", 2: "UECL - PO", 3: "UECL - QR3"}},
    "Israeli Premier League":       {"id": 4644, "country": "Israel",      "flag": "🇮🇱", "season_type": "winter",
                                     "tiebreakers": ["gd", "wins", "gf", "h2h_pts", "h2h_gd", "h2h_gf", "playoffs"],
                                     "european_spots": {1: "UCL - QR3", 2: "UECL - PO", 3: "UECL - PO"},
                                     "split_round": 26, "n_champ": 6, "pts_factor": 1.0},
    "Kazakhstan Premier League":    {"id": 4649, "country": "Kazakhstan",  "flag": "🇰🇿", "season_type": "summer",
                                     "season_end": "26 October 2025",
                                     "tiebreakers": ["gd", "wins", "gf", "away_gf", "h2h_pts", "h2h_wins", "h2h_gd", "h2h_gf", "h2h_away_gf", "draw"],
                                     "european_spots": {1: "UCL - QR1", 2: "UECL - QR2", 3: "UECL - QR2"}},
    "Kosovan Superleague":          {"id": 4968, "country": "Kosovo",      "flag": "🇽🇰", "season_type": "winter",
                                     "tiebreakers": ["h2h_pts", "h2h_gd", "gd", "gf", "playoffs"],
                                     "european_spots": {1: "UCL - QR1", 2: "UECL - QR2", 3: "UECL - QR2"}},
    "Latvian Higher League":        {"id": 4650, "country": "Latvia",      "flag": "🇱🇻", "season_type": "summer",
                                     "season_end": "23 November 2025",
                                     "tiebreakers": ["h2h_pts", "h2h_gd", "gd", "gf", "fair_play", "playoffs"],
                                     "european_spots": {1: "UCL - QR1", 2: "UECL - QR2", 3: "UECL - QR2"}},
    "Lithuanian A Lyga":            {"id": 4651, "country": "Lithuania",   "flag": "🇱🇹", "season_type": "summer",
                                     "season_end": "8 November 2025",
                                     "tiebreakers": ["playoffs_champion", "h2h_pts", "h2h_gd", "h2h_gf", "h2h_wins", "gd", "gf", "wins", "fair_play", "draw"],
                                     "european_spots": {1: "UCL - QR1", 2: "UECL - QR2", 3: "UECL - QR2"}},
    "Luxembourgish National Div":   {"id": 4694, "country": "Luxembourg",  "flag": "🇱🇺", "season_type": "winter",
                                     "tiebreakers": ["gd", "wins", "h2h_pts", "h2h_gd", "h2h_gf", "playoffs"],
                                     "european_spots": {1: "UCL - QR1", 2: "UECL - QR2", 3: "UECL - QR2"}},
    "Macedonian First League":      {"id": 4652, "country": "N. Macedonia","flag": "🇲🇰", "season_type": "winter",
                                     "season_end": "31 May 2026",
                                     "tiebreakers": ["gd", "gf", "h2h_pts", "h2h_gd", "h2h_away_gf", "h2h_gf", "draw", "playoffs"],
                                     "european_spots": {1: "UCL - QR1", 2: "UECL - QR2"}},
    "Maltese Premier League":       {"id": 4653, "country": "Malta",       "flag": "🇲🇹", "season_type": "winter",
                                     "tiebreakers": ["h2h_pts", "h2h_gd", "h2h_gf", "gd", "gf", "playoffs"],
                                     "european_spots": {1: "UCL - QR1", 2: "UECL - QR2", 3: "UECL - QR2"},
                                     "split_round": 11, "n_champ": 6, "pts_factor": 0.0},
    "Moldovan National Division":   {"id": 4655, "country": "Moldova",     "flag": "🇲🇩", "season_type": "winter",
                                     "season_end": "17 May 2026",
                                     "tiebreakers": ["playoffs_champion", "h2h_pts", "h2h_gd", "h2h_gf", "wins", "gd", "gf", "less_red_cards", "less_yellow_cards"],
                                     "european_spots": {1: "UCL - QR2", 2: "UECL - PO", 3: "UECL - QR3"}},
    "Montenegrin First League":     {"id": 4656, "country": "Montenegro",  "flag": "🇲🇪", "season_type": "winter",
                                     "season_end": "4 June 2026",
                                     "tiebreakers": ["h2h_pts", "h2h_gd", "h2h_gf", "gd", "gf", "draw"],
                                     "european_spots": {1: "UCL - QR1", 2: "UECL - QR2", 3: "UECL - QR2"}},
    "Northern Irish Premiership":   {"id": 4659, "country": "N. Ireland",  "flag": "🇬🇧", "season_type": "winter",
                                     "season_end": "26 April 2026",
                                     "tiebreakers": ["gd", "gf", "h2h_pts", "h2h_gd", "draw"],
                                     "european_spots": {1: "UCL - QR1", 2: "UECL - QR2", 3: "UECL - QR2"},
                                     "split_round": 33, "n_champ": 6, "pts_factor": 1.0},
    "Norwegian Eliteserien":        {"id": 4358, "country": "Norway",      "flag": "🇳🇴", "season_type": "summer",
                                     "season_end": "7 December 2025",
                                     "tiebreakers": ["gd", "gf", "h2h_pts", "h2h_gd", "h2h_gf"],
                                     "european_spots": {1: "UCL - PO", 2: "UCL - QR3 (LP)", 3: "UEL - LS", 4: "UECL - LS"},
                                     "zone_notes": {"relegation playoff": "14th plays two-legged play-off against 3rd of OBOS-ligaen. Away goals do not apply; higher-placed team plays second leg at home."}},
    "Polish Ekstraklasa":           {"id": 4422, "country": "Poland",      "flag": "🇵🇱", "season_type": "winter",
                                     "season_end": "23 May 2026",
                                     "tiebreakers": ["h2h_pts", "h2h_gd", "gd", "gf", "wins", "away_wins", "disciplinary", "fair_play", "draw"],
                                     "european_spots": {1: "UCL - QR3", 2: "UEL - PO", 3: "UECL - QR3", 4: "UECL - QR3"},
                                     "zone_notes": {"relegation playoff": "17th plays two-legged play-off against 3rd of I liga. Higher-placed team plays second leg at home."}},
    "Portuguese Primeira Liga":     {"id": 4344, "country": "Portugal",    "flag": "🇵🇹", "season_type": "winter",
                                     "season_end": "17 May 2026",
                                     "tiebreakers": ["h2h_pts", "h2h_gd", "gd", "wins", "gf", "playoffs"],
                                     "european_spots": {1: "UCL - LS", 2: "UCL - PO (LP)", 3: "UEL - QR3", 4: "UECL - PO"}},
    "Romanian Liga I":              {"id": 4691, "country": "Romania",     "flag": "🇷🇴", "season_type": "winter",
                                     "season_end": "24 May 2026",
                                     "tiebreakers": ["h2h_pts", "h2h_gd", "h2h_gf", "gd", "gf", "playoffs"],
                                     "european_spots": {1: "UCL - QR2", 2: "UECL - PO", 3: "UECL - PO"},
                                     "split_round": 30, "n_champ": 6, "pts_factor": 0.5,
                                     "zone_notes": {"relegation": "Bottom two of the Play-out are directly relegated. 7th and 8th in the Play-out play two-legged play-offs against Liga II teams."}},
    "Russian Premier League":       {"id": 4355, "country": "Russia",      "flag": "🇷🇺", "season_type": "winter",
                                     "tiebreakers": ["h2h_pts", "h2h_wins", "h2h_gd", "h2h_gf", "wins", "gd", "gf", "away_wins", "away_gf", "disciplinary", "playoffs"],
                                     "european_spots": {}},
    "San Marino Campionato":        {"id": 4667, "country": "San Marino",  "flag": "🇸🇲", "season_type": "winter",
                                     "season_end": "17 May 2026",
                                     "tiebreakers": ["h2h_pts", "h2h_gd", "h2h_gf", "gd", "gf"],
                                     "european_spots": {1: "UCL - QR1", 2: "UECL - QR2"}},
    "Scottish Premiership":         {"id": 4330, "country": "Scotland",    "flag": "🏴󠁧󠁢󠁳󠁣󠁴󠁿", "season_type": "winter",
                                     "season_end": "26 May 2026",
                                     "tiebreakers": ["gd", "gf", "h2h_pts", "h2h_gd", "playoffs"],
                                     "european_spots": {1: "UCL - PO", 2: "UEL - PO", 3: "UECL - QR3", 4: "UECL - QR3"},
                                     "split_round": 33, "n_champ": 6, "pts_factor": 1.0,
                                     "zone_notes": {"relegation": "11th plays two-legged play-off against 2nd of the Championship. Higher-placed team plays second leg at home. 12th is directly relegated."}},
    "Serbian Super Liga":           {"id": 4671, "country": "Serbia",      "flag": "🇷🇸", "season_type": "winter",
                                     "season_end": "25 May 2026",
                                     "tiebreakers": ["h2h_pts", "h2h_gd", "h2h_gf", "h2h_away_gf", "gd", "gf", "fair_play", "draw"],
                                     "european_spots": {1: "UCL - QR3", 2: "UECL - PO", 3: "UECL - PO"},
                                     "split_round": 30, "n_champ": 8, "pts_factor": 0.5},
    "Slovak First League":          {"id": 4672, "country": "Slovakia",    "flag": "🇸🇰", "season_type": "winter",
                                     "season_end": "23 May 2026",
                                     "tiebreakers": ["h2h_pts", "h2h_gd", "h2h_gf", "h2h_away_gf", "gd", "gf", "fair_play", "draw"],
                                     "european_spots": {1: "UCL - QR2", 2: "UECL - PO", 3: "UECL - PO"},
                                     "split_round": 22, "n_champ": 6, "pts_factor": 1.0,
                                     "zone_notes": {"relegation": "11th plays two-legged play-off against 2nd of Slovak 2. liga. 12th is directly relegated."}},
    "Slovenian 1. SNL":             {"id": 4692, "country": "Slovenia",    "flag": "🇸🇮", "season_type": "winter",
                                     "tiebreakers": ["h2h_pts", "h2h_gd", "h2h_gf", "gd", "gf"],
                                     "european_spots": {1: "UCL - QR2", 2: "UECL - PO", 3: "UECL - PO"}},
    "Swedish Allsvenskan":          {"id": 4347, "country": "Sweden",      "flag": "🇸🇪", "season_type": "summer",
                                     "season_end": "29 November 2025",
                                     "tiebreakers": ["gd", "gf", "h2h_pts", "h2h_gd", "h2h_away_gf", "playoffs"],
                                     "european_spots": {1: "UCL - QR3", 2: "UECL - PO", 3: "UECL - PO"},
                                     "zone_notes": {"relegation playoff": "14th plays two-legged play-off against 3rd of Superettan. Higher-placed club plays second leg at home."}},
    "Swiss Super League":           {"id": 4675, "country": "Switzerland", "flag": "🇨🇭", "season_type": "winter",
                                     "season_end": "23 May 2026",
                                     "tiebreakers": ["gd", "gf", "h2h_gd", "h2h_gf", "away_gf", "draw"],
                                     "european_spots": {1: "UCL - QR3", 2: "UECL - PO", 3: "UECL - PO"},
                                     "split_round": 33, "n_champ": 6, "pts_factor": 1.0,
                                     "zone_notes": {"relegation": "11th plays two-legged play-off against 2nd of Challenge League. 12th is directly relegated."}},
    "Turkish Super Lig":            {"id": 4339, "country": "Turkey",      "flag": "🇹🇷", "season_type": "winter",
                                     "season_end": "17 May 2026",
                                     "tiebreakers": ["h2h_pts", "h2h_gd", "h2h_gf", "gd", "gf", "playoffs"],
                                     "european_spots": {1: "UCL - LS", 2: "UEL - PO", 3: "UEL - QR3", 4: "UECL - QR3"},
                                     "zone_notes": {"relegation playoff": "16th plays two-legged play-off against 3rd of TFF First League. Higher-placed club plays second leg at home."}},
    "Ukrainian Premier League":     {"id": 4354, "country": "Ukraine",     "flag": "🇺🇦", "season_type": "winter",
                                     "season_end": "29 May 2026",
                                     "tiebreakers": ["h2h_pts", "h2h_gd", "h2h_gf", "gd", "gf", "draw"],
                                     "european_spots": {1: "UCL - QR2", 2: "UECL - PO", 3: "UECL - PO"}},
    "Welsh Premier League":         {"id": 4472, "country": "Wales",       "flag": "🏴󠁧󠁢󠁷󠁬󠁳󠁿", "season_type": "winter",
                                     "season_end": "3 May 2026",
                                     "tiebreakers": ["gd", "gf", "h2h_gd", "h2h_gf", "h2h_away_gf", "wins", "away_wins", "playoffs"],
                                     "european_spots": {1: "UCL - QR1", 2: "UECL - QR2", 3: "UECL - QR2"},
                                     "split_round": 22, "n_champ": 6, "pts_factor": 1.0},
}


def get_current_season(season_type: str) -> str:
    """
    Return the TheSportsDB season string currently active.

    Winter leagues (Aug–May):  Jan–Jun → "{year-1}-{year}"  | Jul–Dec → "{year}-{year+1}"
    Summer leagues (Apr–Nov):  Jan–Mar → str(year-1)        | Apr–Dec → str(year)
    """
    from datetime import datetime
    now = datetime.now()
    year = now.year
    if season_type == "summer":
        return str(year)
    return f"{year - 1}-{year}" if now.month < 7 else f"{year}-{year + 1}"


# ---------------------------------------------------------------------------
# UEFA European Competitions (2025-2026)
# IDs sourced from TheSportsDB — verify at thesportsdb.com if data is missing.
#   n_direct  = teams advancing directly to R16 from league phase
#   n_playoff = additional teams entering knockout play-offs
# ---------------------------------------------------------------------------
EUROPEAN_COMPETITIONS = {
    "Champions League": {
        "id": 4480, "flag": "🏆",
        "n_direct": 8, "n_playoff": 16,
        "league_phase_rounds": 8,
        "has_league_phase": True,
        "qualifying_rounds": {400, 1128, 128, 125},
    },
    "Europa League": {
        "id": 4481, "flag": "🥈",
        "n_direct": 8, "n_playoff": 16,
        "league_phase_rounds": 8,
        "has_league_phase": True,
        "qualifying_rounds": {400, 1128, 128, 125},
    },
    "Conference League": {
        "id": 5071, "flag": "🏅",
        "n_direct": 8, "n_playoff": 16,
        "league_phase_rounds": 8,
        "has_league_phase": True,
        "qualifying_rounds": {400, 1128, 128, 125},
    },
}

# Default API key — the public demo key (limited to 5 standings rows / 15 fixtures).
# Subscribe at thesportsdb.com (Single Developer $9/mo) for full data.
# Set env var THESPORTSDB_API_KEY or enter in the sidebar.
DEFAULT_API_KEY = "3"

# Simulation defaults
DEFAULT_N_SIMULATIONS = 10_000
DEFAULT_HOME_ADVANTAGE = 1.20
DEFAULT_BASE_GOALS = 1.35

# Cache TTL in seconds
CACHE_TTL_STANDINGS = 7_200     # 2 hours
CACHE_TTL_FIXTURES = 3_600      # 1 hour
CACHE_TTL_META = 86_400         # 24 hours
